### ISSUE TITLE
--att 使用没成功

### ISSUE THREAD

**Issue by lppyyy** [li8u99/yonyou_exp_plus#1]
出现了这个提示![图片](https://user-images.githubusercontent.com/103994446/221129139-0efd6623-060f-438b-a6f4-b92f1214315b.png)

**Comment by li8u99** [comment]
是用python3运行的么

**Comment by lppyyy** [comment]
是的，我看语句可能是没对返还的状态码异常处理，返还的值不是200，然后报错了

**Comment by li8u99** [comment]
已更新，感谢反馈
